/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_co_halfninja_videokit_Videokit */

#ifndef _Included_com_starrinme_challenge_ffmpeg_Videokit
#define _Included_com_starrinme_challenge_ffmpeg_Videokit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_starrinme_challenge_ffmpeg_Videokit
 * Method:    run
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT jboolean JNICALL Java_com_starrinme_challenge_ffmpeg_Videokit_run
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
